# @name jitPoliciesList
GET {{ $dotenv %baseUrl }}/api/jits/list?{{ $dotenv %authCode }}g={{ $dotenv %resourceGroup }} HTTP/1.1
Accept: application/json

###

GET {{ $dotenv %baseUrl }}/api/jits/get?{{ $dotenv %authCode }}g={{ $dotenv %resourceGroup }}&policyName={{ $dotenv %policyName }} HTTP/1.1
Accept: application/json

###

POST {{ $dotenv %baseUrl }}/api/jits/initiate?{{ $dotenv %authCode }}g={{ $dotenv %resourceGroup }}&vm={{ $dotenv %vm }}&policyName={{ $dotenv %policyName }} HTTP/1.1
Accept: application/json

###

POST {{ $dotenv %baseUrl }}/api/jits/createOrUpdate?{{ $dotenv %authCode }}g={{ $dotenv %resourceGroup }}&vm={{ $dotenv %vm }}&policyName={{ $dotenv %policyName }} HTTP/1.1
Accept: application/json

###
